language: elixir
git:
  depth: 1000
cache:
  directories:
  - _build
  - deps
services:
- docker
- postgresql
addons:
  postgresql: '9.6'
  apt:
    packages:
    - postgresql-9.6-postgis-2.3
    - docker-ce
elixir:
- 1.6.3
otp_release:
- 20.2.2
env:
  global:
  - MIX_ENV=test
  - APPS='{"sandbox_api":"sandbox"}'
  - POSTGRES_VERSION=9.6
  - DOCKER_USERNAME=devildriver
  - secure: "W/Bznmp+aIB9bGsI0JhDHlHER6fCbCwjVzNXbltT5na/eqneZMtMOcKPUBr3cqw3Nf9VVMxxosWkHAftFARuCZzelqLsSokiGi+7oIlsKFUM7+bour76lSPeas2XavDKBuP+TkztnpYxyEMDqRubPAPUM3SOs+3zZfR2RTeBa+GzWaf2bOvlQ2osQGY+RAGm71h1XXBnzHiCv/003EzZkNplNGkTzL013dv2UH6hZsyfPlRxKhNDOFblzIPPOjGBebkQ99O6Cc0FyUOos/UktHdMlkcOqXCG8MrDGZXNTrpGDzp7+GHjFwRfSI0R7tuzHBO7T9yigAZxplK4L73XgJiJFsZN5RokCDDXNAf4lYuUXVlUx8ryqTtspCOP3yYS85efOxfz6JruHYSoPAERtpvzShYAwlXklEBqUwUO0/o352p0U0okdY+qZJZC1HZ9s2gWj5k1b1Vk46A63GcFSGp+6ct5nbD/1qGeR1vmB+lYgcYhlyyomsgpwOhGLbSv0ttIdVQJ5JMfbOL9uQb/qxnvcPAaIrFda81vPEbhvyKXYO3ycXUsQY8ZWjpMybFsnbCWxP6v25qGG62PVBA4uDOobRPHC+EXbkto3wUO7i1aZU8E7lKG76WPUsnSiLz1zatTRbZrFzGVvmyxF768YhvC02hNMmEb2Rx2o0M6yGA="
branches:
  except:
  - "/[0-9]*\\.[0-9]*\\.[0-9]*/"
before_install:
- sudo apt-get install jq
- curl -s https://raw.githubusercontent.com/edenlabllc/ci-utils/umbrella/init-db.sh -o init-db.sh; sudo sh ./init-db.sh
before_script:
- curl -s https://raw.githubusercontent.com/edenlabllc/ci-utils/umbrella/init-version.sh -o init-version.sh; source ./init-version.sh
jobs:
  include:
    - stage: "test and build"
      # run tests
      script: (curl -s https://raw.githubusercontent.com/edenlabllc/ci-utils/umbrella/tests.sh -o tests.sh; bash ./tests.sh) || travis_terminate 1
      # Build Docker container
    - stage: "test and build"
      script: (curl -s https://raw.githubusercontent.com/edenlabllc/ci-utils/umbrella/build-container.sh -o build-container.sh; bash ./build-container.sh) || travis_terminate 1
    # Start Docker container
    - stage: docker
      script: (curl -s https://raw.githubusercontent.com/edenlabllc/ci-utils/umbrella/start-container.sh -o start-container.sh; bash ./start-container.sh) || travis_terminate 1
    # Push container
    - stage: push
      script: (curl -s https://raw.githubusercontent.com/edenlabllc/ci-utils/umbrella/push-changes.sh -o push-changes.sh; bash ./push-changes.sh) || travis_terminate 1
      # "Decrypting deploy key..."
      # - script:  openssl aes-256-cbc -K $encrypted_c996ec964e08_key -iv $encrypted_c996ec964e08_iv -in eHealth-8110bd102a69.json.enc -out eHealth-8110bd102a69.json -d
    - stage: autodeploy
      script: (curl -s https://raw.githubusercontent.com/edenlabllc/ci-utils/umbrella/autodeploy.sh -o autodeploy.sh; bash ./autodeploy.sh) || travis_terminate 1
