language: elixir
git:
  depth: 1000
cache:
  directories:
  - _build
  - deps
services:
- docker
- postgresql
addons:
  postgresql: '9.6'
  apt:
    packages:
    - postgresql-9.6-postgis-2.3
    - docker-ce
elixir:
- 1.6.3
otp_release:
- 20.2.2
env:
  global:
  - MIX_ENV=test
  - APPS='["sandbox_api"]'
  - POSTGRES_VERSION=9.6
  - DOCKER_HUB_LOGIN=devildriver
  - secure: S/P0vPp6C/8GsRqM8QvMnmKGnhuScKIkz0ZYVN9k8tg4ks/FxWkc8rr0mBMYPwTaRdeKExMyM4yLJzhclLDqU+6SYYJxb86G8yhxPM0powF4xoXr9FY8EQREbr/fgg16YsNvq5HBeUyCm5zCLGl4s0sFaWGz1D+unxSbiMaRqZgJqpMU8ocsmtODDTxqlAyjDb5NDUhfzWIzWSBctJMoomCiV0tsJAJsGF86qNhHbERBNSYV+2mZgU5VWEXHpDPowgLM096uv71hGFF+nUwwYn4uquVPegPncsXx+1cjLgTzoUi7m0nzAKCOwsxCl/O6Ilu8yNIgMuNsLGBjRGMbCYkKHuD5Wf2YoEgx6z/7SHraIW0SFtDqQ2DufnEr3IVv2ObgAMLgYMxRoJ8d48jlbRe5W8yMHooKUyZ5fLEKii4GrrAFzzNhq+UBwC5sNDpXyOMGuej0g+x996OI1YzmacxgGKtPNfDSmWHKz5AZ+yPv/0f/RUBHJpSYYrfh1W3gprE4qDJs0y87i3ubz9YJwXO5ZWNO0IOsRd9ub4BFfMFbzvsSSgN3brIvMEkkXUl7YCz/7XSuJM/WXInchLanlTUXp8+oDzOODkAalsBTBwaTn1jNv+ACdnZQF5AJY51/2sKcRmL2Jcm3Jic9ieBCvj6Fl3CF1V/j6UcBwoONXos=
branches:
  except:
  - "/[0-9]*\\.[0-9]*\\.[0-9]*/"
before_install:
- sudo apt-get install jq
- curl -s https://raw.githubusercontent.com/edenlabllc/ci-utils/umbrella/init-db.sh
  | sudo sh
before_script:
- curl -s https://raw.githubusercontent.com/edenlabllc/ci-utils/umbrella/init-version.sh
  | bash
script:
  # Run all tests except pending ones
  - curl -s https://raw.githubusercontent.com/edenlabllc/ci-utils/umbrella/tests.sh | bash || travis_terminate 1
  # Build Docker container
  - curl -s https://raw.githubusercontent.com/edenlabllc/ci-utils/umbrella/build-container.sh | bash || travis_terminate 1
